#
#   ██████╗██████╗ ██╗███╗  ██╗███╗  ██╗██╗███╗  ██╗
#  ██╔════╝██╔══██╗██║████╗ ██║████╗ ██║██║████╗ ██║
#  ╚█████╗░██████╔╝██║██╔██╗██║██╔██╗██║██║██╔██╗██║
#   ╚═══██╗██╔═══╝ ██║██║╚████║██║╚████║██║██║╚████║
#  ██████╔╝██║     ██║██║ ╚███║██║ ╚███║██║██║ ╚███║
#  ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚══╝╚═╝  ╚══╝╚═╝╚═╝  ╚══╝
#

roles:
  default:
    rows: 2
    max_backpacks: 1
  vip:
    rows: 5
    max_backpacks: 2